---
- hosts: webhost
  tasks: 
   - name: Install httpd service 
     yum: name=httpd state=latest
   
   - name: Add website code index.html
     copy: src=index.html dest=/var/www/html/index.html owner=root group=root mode=0644
     
   - name: start httpd service 
     service: name=httpd state=started enabled=yes
